import type {
  Transfer,
  AuditEvent,
  TransferStatus,
  UserRole,
} from '../../modules/transferencias/types'

const generateId = () => Math.random().toString(36).substring(2, 10)

const baseDate = new Date('2025-11-03T08:00:00')

const getTime = (minutesToAdd: number) => {
  const date = new Date(baseDate)
  date.setMinutes(date.getMinutes() + minutesToAdd)
  return date.toISOString()
}

const generateAuditEvent = (
  transferencia_id: string,
  actor: string,
  rol: UserRole,
  accion: string,
  estado_nuevo: TransferStatus,
  descripcion: string,
  timestamp: string,
  estado_anterior?: TransferStatus,
  datos_adicionales?: Record<string, unknown>,
): AuditEvent => ({
  id: generateId(),
  transferencia_id,
  actor,
  rol,
  accion,
  estado_anterior,
  estado_nuevo,
  descripcion,
  timestamp,
  datos_adicionales,
})

export const initialTransfers: Transfer[] = [
  {
    id: 'TRF-2025-0441',
    producto: 'Filtro hidráulico HF-220',
    cantidad: 5,
    cantidad_recibida: 5,
    diferencia: 0,
    origen: 'Bodega Norte',
    destino: 'Bodega Sur',
    prioridad: 'urgente',
    estado: 'RECIBIDA_SIN_DIFERENCIA',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(0),
    fecha_actualizacion: getTime(260),
    descripcion: 'Mantenciones programadas días 3 y 5',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0441',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada para reponer stock crítico en Bodega Sur',
        getTime(0),
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Rodrigo',
        'supervisor_solicitante',
        'seleccionar_origen',
        'CREADA',
        'Se selecciona Bodega Norte como bodega de origen',
        getTime(10),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Sistema',
        'sistema',
        'validar_stock_real',
        'CREADA',
        'Validación de stock real exitosa con bloqueo pesimista',
        getTime(18),
        'CREADA',
        {
          stock_total: 22,
          stock_comprometido: 6,
          stock_disponible_real: 16,
        },
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Carlos',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada por supervisor remitente',
        getTime(40),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Sistema',
        'sistema',
        'reservar_stock',
        'RESERVADA',
        'Reserva de stock ejecutada correctamente',
        getTime(50),
        'APROBADA',
        {
          reservado: 5,
          bodega: 'Bodega Norte',
        },
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Pedro',
        'operario_despacho',
        'registrar_despacho',
        'EN_TRANSITO',
        'Despacho registrado con 5 unidades',
        getTime(120),
        'RESERVADA',
      ),
      generateAuditEvent(
        'TRF-2025-0441',
        'Miguel',
        'operario_recepcion',
        'registrar_recepcion',
        'RECIBIDA_SIN_DIFERENCIA',
        'Recepción conforme sin diferencias',
        getTime(250),
        'EN_TRANSITO',
        {
          cantidad_conforme: 5,
          cantidad_no_conforme: 0,
        },
      ),
    ],
  },
  {
    id: 'TRF-2025-0442',
    producto: 'Rodamiento industrial RB-310',
    cantidad: 8,
    cantidad_recibida: 6,
    diferencia: 2,
    origen: 'Bodega Centro',
    destino: 'Bodega Sur',
    prioridad: 'alta',
    estado: 'CON_DIFERENCIA',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(15),
    fecha_actualizacion: getTime(310),
    descripcion: 'Reposición para mantenimiento correctivo',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0442',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada por necesidad operativa',
        getTime(15),
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Sistema',
        'sistema',
        'validar_stock_real',
        'CREADA',
        'Validación de stock real exitosa en Bodega Centro',
        getTime(24),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Patricia',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada por supervisor remitente',
        getTime(35),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Sistema',
        'sistema',
        'reservar_stock',
        'RESERVADA',
        'Reserva de 8 unidades realizada',
        getTime(45),
        'APROBADA',
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Pedro',
        'operario_despacho',
        'registrar_despacho',
        'EN_TRANSITO',
        'Despacho registrado con 8 unidades',
        getTime(100),
        'RESERVADA',
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Miguel',
        'operario_recepcion',
        'registrar_recepcion',
        'CON_DIFERENCIA',
        'Recepción con faltante de 2 unidades',
        getTime(300),
        'EN_TRANSITO',
        {
          cantidad_conforme: 6,
          cantidad_no_conforme: 0,
          faltante: 2,
        },
      ),
      generateAuditEvent(
        'TRF-2025-0442',
        'Rodrigo',
        'supervisor_solicitante',
        'registrar_diferencia',
        'CON_DIFERENCIA',
        'Supervisor solicitante confirma diferencia de cantidad',
        getTime(310),
        'CON_DIFERENCIA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0443',
    producto: 'Sello mecánico SM-90',
    cantidad: 12,
    origen: 'Bodega Norte',
    destino: 'Bodega Oriente',
    prioridad: 'normal',
    estado: 'APROBADA',
    creada_por: 'Camila',
    fecha_creacion: getTime(30),
    fecha_actualizacion: getTime(95),
    descripcion: 'Solicitud aprobada pendiente de reserva',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0443',
        'Camila',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada para reposición programada',
        getTime(30),
      ),
      generateAuditEvent(
        'TRF-2025-0443',
        'Sistema',
        'sistema',
        'validar_stock_real',
        'CREADA',
        'Stock real validado correctamente',
        getTime(50),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0443',
        'Carlos',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada y pendiente de reserva',
        getTime(95),
        'CREADA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0444',
    producto: 'Correa de transmisión CT-500',
    cantidad: 20,
    origen: 'Bodega Centro',
    destino: 'Bodega Sur',
    prioridad: 'alta',
    estado: 'RESERVADA',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(45),
    fecha_actualizacion: getTime(130),
    descripcion: 'Reserva realizada, pendiente de preparación de despacho',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0444',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada',
        getTime(45),
      ),
      generateAuditEvent(
        'TRF-2025-0444',
        'Patricia',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada por supervisor remitente',
        getTime(70),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0444',
        'Sistema',
        'sistema',
        'reservar_stock',
        'RESERVADA',
        'Reserva completada, esperando preparación de despacho',
        getTime(130),
        'APROBADA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0445',
    producto: 'Válvula de presión VP-12',
    cantidad: 14,
    origen: 'Bodega Norte',
    destino: 'Bodega Poniente',
    prioridad: 'urgente',
    estado: 'ERROR_RESERVA',
    creada_por: 'Valentina',
    fecha_creacion: getTime(55),
    fecha_actualizacion: getTime(145),
    descripcion: 'Fallo técnico al ejecutar la reserva',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0445',
        'Valentina',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada con prioridad urgente',
        getTime(55),
      ),
      generateAuditEvent(
        'TRF-2025-0445',
        'Carlos',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada por supervisor remitente',
        getTime(90),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0445',
        'Sistema',
        'sistema',
        'error_reserva',
        'ERROR_RESERVA',
        'Fallo técnico durante la operación de reserva',
        getTime(145),
        'APROBADA',
        {
          motivo: 'timeout_bloqueo',
          reintentos: 3,
        },
      ),
    ],
  },
  {
    id: 'TRF-2025-0446',
    producto: 'Filtro hidráulico HF-220',
    cantidad: 9,
    origen: 'Bodega Norte',
    destino: 'Bodega Sur',
    prioridad: 'normal',
    estado: 'RECHAZADA',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(65),
    fecha_actualizacion: getTime(110),
    descripcion: 'Solicitud rechazada por impacto operacional en bodega origen',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0446',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada',
        getTime(65),
      ),
      generateAuditEvent(
        'TRF-2025-0446',
        'Carlos',
        'supervisor_remitente',
        'rechazar_solicitud',
        'RECHAZADA',
        'Solicitud rechazada con justificación por demanda interna crítica',
        getTime(110),
        'CREADA',
        {
          justificacion:
            'La bodega origen necesita mantener stock mínimo de seguridad para operación local',
        },
      ),
    ],
  },
  {
    id: 'TRF-2025-0447',
    producto: 'Sensor térmico ST-88',
    cantidad: 6,
    origen: 'Sin origen asignado',
    destino: 'Bodega Sur',
    prioridad: 'alta',
    estado: 'SIN_ORIGEN_DISPONIBLE',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(75),
    fecha_actualizacion: getTime(140),
    descripcion: 'No se encontró bodega origen viable tras reintentos',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0447',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada para evaluar alternativas de origen',
        getTime(75),
      ),
      generateAuditEvent(
        'TRF-2025-0447',
        'Rodrigo',
        'supervisor_solicitante',
        'seleccionar_origen',
        'CREADA',
        'Se intenta inicialmente con Bodega Norte',
        getTime(85),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0447',
        'Sistema',
        'sistema',
        'validar_stock_real_fallido',
        'CREADA',
        'Stock insuficiente en Bodega Norte, se descarta candidata',
        getTime(100),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0447',
        'Rodrigo',
        'supervisor_solicitante',
        'reintentar_seleccion_origen',
        'CREADA',
        'Se reintenta con Bodega Centro',
        getTime(115),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0447',
        'Sistema',
        'sistema',
        'sin_origen_disponible',
        'SIN_ORIGEN_DISPONIBLE',
        'Se agotan candidatas y la solicitud queda sin origen disponible',
        getTime(140),
        'CREADA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0448',
    producto: 'Acople flexible AF-77',
    cantidad: 4,
    origen: 'Bodega Centro',
    destino: 'Bodega Norte',
    prioridad: 'urgente',
    estado: 'ESCALADA',
    creada_por: 'Camila',
    fecha_creacion: getTime(85),
    fecha_actualizacion: getTime(360),
    descripcion: 'Supervisor remitente no respondió dentro del plazo',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0448',
        'Camila',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada con prioridad urgente',
        getTime(85),
      ),
      generateAuditEvent(
        'TRF-2025-0448',
        'Sistema',
        'sistema',
        'escalar_solicitud',
        'ESCALADA',
        'Plazo de respuesta vencido sin acción del supervisor remitente',
        getTime(360),
        'CREADA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0449',
    producto: 'Manguera industrial MI-200',
    cantidad: 10,
    origen: 'Bodega Norte',
    destino: 'Bodega Sur',
    prioridad: 'alta',
    estado: 'EN_TRANSITO',
    creada_por: 'Rodrigo',
    fecha_creacion: getTime(95),
    fecha_actualizacion: getTime(210),
    descripcion: 'Despacho realizado, pendiente de recepción',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0449',
        'Rodrigo',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada',
        getTime(95),
      ),
      generateAuditEvent(
        'TRF-2025-0449',
        'Carlos',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada',
        getTime(125),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0449',
        'Sistema',
        'sistema',
        'reservar_stock',
        'RESERVADA',
        'Stock reservado correctamente',
        getTime(140),
        'APROBADA',
      ),
      generateAuditEvent(
        'TRF-2025-0449',
        'Pedro',
        'operario_despacho',
        'registrar_despacho',
        'EN_TRANSITO',
        'Despacho registrado y transferencia en tránsito',
        getTime(210),
        'RESERVADA',
      ),
    ],
  },
  {
    id: 'TRF-2025-0450',
    producto: 'Empaque técnico ET-15',
    cantidad: 7,
    cantidad_recibida: 7,
    diferencia: 0,
    origen: 'Bodega Centro',
    destino: 'Bodega Oriente',
    prioridad: 'baja',
    estado: 'CERRADA',
    creada_por: 'Camila',
    fecha_creacion: getTime(5),
    fecha_actualizacion: getTime(420),
    descripcion: 'Transferencia finalizada y cerrada',
    eventos: [
      generateAuditEvent(
        'TRF-2025-0450',
        'Camila',
        'supervisor_solicitante',
        'crear_solicitud',
        'CREADA',
        'Solicitud creada',
        getTime(5),
      ),
      generateAuditEvent(
        'TRF-2025-0450',
        'Patricia',
        'supervisor_remitente',
        'aprobar_solicitud',
        'APROBADA',
        'Solicitud aprobada por supervisor remitente',
        getTime(25),
        'CREADA',
      ),
      generateAuditEvent(
        'TRF-2025-0450',
        'Sistema',
        'sistema',
        'reservar_stock',
        'RESERVADA',
        'Reserva ejecutada correctamente',
        getTime(40),
        'APROBADA',
      ),
      generateAuditEvent(
        'TRF-2025-0450',
        'Pedro',
        'operario_despacho',
        'registrar_despacho',
        'EN_TRANSITO',
        'Despacho confirmado',
        getTime(90),
        'RESERVADA',
      ),
      generateAuditEvent(
        'TRF-2025-0450',
        'Miguel',
        'operario_recepcion',
        'registrar_recepcion',
        'RECIBIDA_SIN_DIFERENCIA',
        'Recepción sin diferencias',
        getTime(180),
        'EN_TRANSITO',
      ),
      generateAuditEvent(
        'TRF-2025-0450',
        'Sistema',
        'sistema',
        'cerrar_transferencia',
        'CERRADA',
        'Transferencia cerrada tras validación final',
        getTime(420),
        'RECIBIDA_SIN_DIFERENCIA',
      ),
    ],
  },
]