export const TRANSFER_STATUS = {
  CREADA: 'CREADA',
  APROBADA: 'APROBADA',
  RESERVADA: 'RESERVADA',
  EN_TRANSITO: 'EN_TRANSITO',
  EN_TRANSITO_CON_INCIDENTE: 'EN_TRANSITO_CON_INCIDENTE',
  RECIBIDA_SIN_DIFERENCIA: 'RECIBIDA_SIN_DIFERENCIA',
  CON_DIFERENCIA: 'CON_DIFERENCIA',
  CERRADA: 'CERRADA',
  RECHAZADA: 'RECHAZADA',
  SIN_ORIGEN_DISPONIBLE: 'SIN_ORIGEN_DISPONIBLE',
  ERROR_RESERVA: 'ERROR_RESERVA',
  ESCALADA: 'ESCALADA',
} as const

export const TRANSFER_STATUS_LABELS = {
  CREADA: 'Creada',
  APROBADA: 'Aprobada',
  RESERVADA: 'Reservada',
  EN_TRANSITO: 'En tránsito',
  EN_TRANSITO_CON_INCIDENTE: 'En tránsito con incidente',
  RECIBIDA_SIN_DIFERENCIA: 'Recibida OK',
  CON_DIFERENCIA: 'Con diferencia',
  CERRADA: 'Cerrada',
  RECHAZADA: 'Rechazada',
  SIN_ORIGEN_DISPONIBLE: 'Sin origen disponible',
  ERROR_RESERVA: 'Error de reserva',
  ESCALADA: 'Escalada',
} as const

export const TRANSFER_STATUS_COLORS = {
  CREADA: 'slate',
  APROBADA: 'blue',
  RESERVADA: 'cyan',
  EN_TRANSITO: 'purple',
  EN_TRANSITO_CON_INCIDENTE: 'fuchsia',
  RECIBIDA_SIN_DIFERENCIA: 'green',
  CON_DIFERENCIA: 'orange',
  CERRADA: 'emerald',
  RECHAZADA: 'red',
  SIN_ORIGEN_DISPONIBLE: 'rose',
  ERROR_RESERVA: 'red',
  ESCALADA: 'amber',
} as const